CREATE TABLE [Competitors].[WorkoutDate]
(
  [WorkoutDateId] INT NOT NULL IDENTITY (1, 1)
, [Date] DATE NOT NULL
, [Comment] VARCHAR(2000) NOT NULL
, CONSTRAINT PK_WorkoutDate PRIMARY KEY CLUSTERED ( [WorkoutDateId] )
)
GO
CREATE UNIQUE NONCLUSTERED INDEX AK_WorkoutDateDate ON [Competitors].[WorkoutDate]
(
	[Date] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
